---
- name: Install - Add Repositories
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/
    gpgkey:
      - https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/rpm/repodata/repomd.xml.key


- name: Install - Add Repositories GPG keys
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg


- name: Install - Kubelet
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present


- name: Install - Kubelet Enable
  service:
    name: kubelet
    enabled: true
    daemon_reload: yes
