---
- name: Master - Check if a cluster already exists
  stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: cluster


- name: Master - Gen Cert
  command: >
    kubeadm init phase upload-certs --upload-certs
  register: cert
  delegate_to: "{{ groups.masters | first }}"
  run_once: true


- name: Master - Get Master IP
  set_fact:
    kubernetes_cluster_apiserver_ip: "{{ hostvars[inventory_hostname]['ansible_' + kubernetes_master_iface].ipv4.address }}"


- name: Master - Join
  command: >
    {{ join_command.stdout_lines[0] }}
    --apiserver-advertise-address {{ kubernetes_cluster_apiserver_ip }}
    --apiserver-bind-port {{ kubernetes_cluster_apiserver_port }}
    --control-plane
    --certificate-key {{ cert.stdout_lines[2] }}
    {{ kubernetes_master_join_command_extra_opts }}
  when:
    - not cluster.stat.exists
  throttle: 1


- name: Master - Create .kube folder
  file:
    path: ~/.kube
    state: directory
    mode: 0755


- name: Master - Copy the kubectl admin.conf to ~/.kube/config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    remote_src: yes
    mode: 0644


- name: Master - Get kubeconfig to Ansible Master
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: ./build/kubeconfig
    flat: yes
  delegate_to: "{{ groups.masters | first }}"
  run_once: true
