---
- name: Post-Install - Get Kubernetes Version for Weave
  shell: >
    kubectl version | base64 | tr -d '\n'
  register: weave_k8s_version
  run_once: true


- name: Post-Install - Install Weave
  command: >
    kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
  register: weave
  changed_when: "'created' in weave.stdout"
  run_once: true
